---
- hosts: all
  roles:
    - dkim
    - { role: packages, become: yes }
    - { role: firewall, become: yes }
    - dirs
    - { role: geerlingguy.docker, become: yes }
    - { role: postgresdocker, become: yes }
    - { role: postfix, become: yes }
    - { role: sl, become: yes }
    - { role: nginx, become: yes }
    - finalize
  vars_files:
    - vars/main.yml